apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


labels:
- includeSelectors: true
  pairs:
    environment: staging

resources:
- ../../base

patches:
- path: replica-count.yaml
- path: resource-limits.yaml
