apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  template:
    spec:
      containers:
      - name: rng
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi