apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  template:
    spec:
      containers:
      - name: rng
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi