apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


labels:
- includeSelectors: true
  pairs:
    environment: noweb

resources:
- ../../base

#patches:
#- path: delete-deploy-web-ui.yaml
# ou
patches:
- target:
    kind: Deployment
    name: webui
  patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: webui

patches:
- target:
    kind: Deployment
    name: worker
  patch: |-
  spec:
    replicas: 5
